Update README to address terminology confusion.
IBM/satcon-client-go pull request #32
Opened 2021-03-22 20:25 UTC by steven-collins-omega

In passing address official open-source Razee support

2021-03-22 20:57 UTC, ScarletTanager requested changes
A couple of tweaks requested.

2021-03-22 20:57 UTC, ScarletTanager commented on README.md
> +1. **Register a cluster to SatCon.**  This makes the cluster known to SatCon, and the API call will return the URL for a Kubernetes yaml file which can be applied to the actual cluster.  This yaml wi
Change `This yaml` to `Applying this yaml via e.g. kubectl` or similar.

2021-03-22 20:57 UTC, ScarletTanager commented on README.md
> +1. **Add the cluster to one or more groups.**  If no group exists in the IBM Cloud account, you will first need to create a group.  You can then add your cluster to the group.
I would prefer, `within the organization (i.e. the IBM Cloud account)` - I think that we should make sure to use both terms everywhere we use one or the other for now.

2021-03-23 18:19 UTC, steven-collins-omega commented
@ScarletTanager tweaks made along with a couple of other minor improvements.

2021-03-23 18:23 UTC, ScarletTanager approved these changes
Wazinga!

2021-03-23 18:26 UTC, merged